# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48b95bdb2ec1c9ac87d3b26dcc89182fc193cfbe5e4ede96996c286fd3c193579a708a3ab4c30778a8e231a04815bd43f0a34ad5068e84b0e1bdb509d7990063

test:
  secret_key_base: b1bf9eb9b2907ead5ca9a7a6ac326542eac4a33cb26c5623a1ae53af41cdeba389f1e143ffa801c263f23fa773f25fc5f4b1618c91447d4c50aee491d29f983a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
